{% set name = "google-cloud-cpp-common" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9ef2bb9b731cade7eb1be7e45323becb78cecda7e39b0a4050d7b787425d5efb

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("google-cloud-cpp-common", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - c-ares
    - googleapis-cpp
    - grpc-cpp
  run:

test:
  commands:
    - test -f $PREFIX/lib/libgoogle_cloud_cpp_common${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/google/cloud/version.h  # [unix]
    - test -f $PREFIX/lib/cmake/google_cloud_cpp_common/google_cloud_cpp_common-config.cmake  # [unix]

about:
  home: https://github.com/googleapis/google-cloud-cpp-common
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud C++ client common libraries

extra:
  recipe-maintainers:
    - xhochy
